name: keyboard_overlay
description: A simple way to show overlay widgets when keyboard rises, without changing widget three from your current project
version: 1.0.0
homepage: https://github.com/emanuel-braz/keyboard_overlay

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

